version: "3.8"
services:
  back:
    build: ./packages/back
    ports:
      - "3000:3000"
      - "9229:9229"
    networks:
      - moovy-network
    volumes:
      - $PWD/packages/back:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
    depends_on:
      - "db"

  front:
    build: ./packages/front
    ports:
      - "3333:3333"
    networks:
      - moovy-network
    volumes:
      - $PWD/packages/front:/usr/src/app
      - /usr/src/app/node_modules

  db:
    container_name: moovy-postgres
    image: postgres:14.2-alpine
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - moovy-network

  pgadmin:
    image: dpage/pgadmin4:6.8
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "123"
    ports:
      - "15432:80"
    depends_on:
      - db
    networks:
      - moovy-network

volumes:
  db:
    driver: local

networks:
  moovy-network:
    external: true
