version: "3.8"
services:
  postgres:
    container_name: moovy-postgres
    image: postgres:14.2-alpine
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  back:
    build:
      context: ./packages/back
      dockerfile: Dockerfile.prod
    ports:
      - "3000:3000"
    environment:
      - DATABASE_HOST=moovy-postgres
      - DATABASE_NAME=moovy
      - DATABASE_USER=admin
      - DATABASE_PASSWORD=123
      - DATABASE_PORT=5432
    restart: unless-stopped
    depends_on:
      - "postgres"

  front:
    build:
      context: ./packages/front
      dockerfile: Dockerfile.prod
    ports:
      - "3333:80"
    depends_on:
      - "back"

volumes:
  postgres:
    driver: local
