version: "3.8"
services:
  postgres:
    container_name: moovy-postgres
    image: postgres:14.2-alpine
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  back:
    build: ./packages/back
    ports:
      - "3000:3000"
    environment:
      - DATABASE_HOST=moovy-postgres
      - DATABASE_NAME=moovy
      - DATABASE_USER=admin
      - DATABASE_PASSWORD=123
      - DATABASE_PORT=5432
    volumes:
      - $PWD/packages/back:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
    depends_on:
      - "postgres"

  front:
    build: ./packages/front
    ports:
      - "3333:3333"
    volumes:
      - $PWD/packages/front:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - "back"

  pgadmin:
    image: dpage/pgadmin4:6.8
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "123"
    ports:
      - "15432:80"

volumes:
  postgres:
    driver: local
